// Editá las consignas directamente en este archivo desde GitHub.
// Formato de cada entrada: ['emoji de categoría', 'consigna']
// Conservá las comas, comillas y corchetes para que la aplicación siga funcionando.
const seeds = [
  ['✈️','TOP-3 lugares del mundo a los que volverías a ir'],
  ['✈️','TOP-3 lugares del mundo que te gustaría visitar que aún no visitaste'],
  ['🎮','TOP-3 videojuegos que jugas cuando tenes un rato'],
  ['🎮','TOP-3 videojuegos que te emocionan'],
  ['🎮','TOP-3 libros que recomendas'],
  ['⚽','TOP-3 Deportes que menos te gustan'],
  ['⚽','TOP-3 Deportes para ver'],
  ['⚽','TOP-3 Deportes para hacer'],
  ['🤔','TOP-3 señales que una persona te va a caer bien'],
  ['🤔','TOP-3 señales que una persona te va a caer mal (prejuicios)'],
  ['🤔','TOP-3 excusas para cancelar un plan'],
  ['🎬','TOP-3 películas para un roadtrip'],
  ['🎬','TOP-3 peliculas de acción'],
  ['🎬','TOP-3 peliculas de terror'],
  ['🎬','TOP-3 peliculas enfermas'],
  ['🎬','TOP-3 peliculas de drama'],
  ['🎬','TOP-3 peliculas relacionadas con música (no musicales)'],
  ['🎬','TOP-3 heroes de acción'],
  ['🎬','TOP-3 villanos del cine'],
  ['🎬','TOP-3 sitcoms'],
  ['🎵','TOP-3 bandas que te gustaría ver en vivo que aún no viste'],
  ['🎵','TOP-3 canciones para cantar'],
  ['🎵','TOP-3 canciones para un día de lluvia'],
  ['🎵','TOP-3 canciones para la mañana del Domingo'],
  ['🎵','TOP-3 canciones para escuchar a todo volumen en el auto'],
  ['🍕','TOP-3 comidas que elegirías para tu última cena'],
  ['🍕','TOP-3 combinaciones de pizza'],
  ['🍕','TOP-3 de empanadas'],
  ['🍕','TOP-3 de facturas'],
  ['🍕','TOP-3 de formas de comer papa'],
  ['🍕','TOP-3 de formas de comer queso'],
  ['🍕','TOP-3 de ingredientes de picada'],
  ['❤️','TOP-3 planes perfectos para una primera cita']];
